name: Deploy website to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: ['main']
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# Provide permission to clone the repo and deploy it to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  # Prepare static website artifact
  build:
    if: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          # Full history is not required but safe for future needs
        fetch-depth: 0

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5

    - name: Prepare static files
      run: |
        mkdir -p _site
        rsync -av --delete \
          --exclude '.git/' \
          --exclude '.github/' \
          --exclude '_site/' \
          --exclude 'another/' \
          ./ _site/

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./_site

  # Deploy website to GitHub Pages hosting
  deploy:
    if: false
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4